### ISSUE TITLE
[Bug] The Runtime module start/stop script cannot be executed on linux

### ISSUE THREAD

**Issue by g0715158** [apache/eventmesh#4299]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux

### EventMesh version

master

### What happened

The Runtime module start/stop script cannot be executed on linux

### How to reproduce

sh start.sh

bin/start.sh:行19: $'\r': 未找到命令
: 无效选项sh: 第 23 行:set: -
set: 用法:set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by g0715158** [comment]
dos2unix this script

**Comment by Pil0tXia** [comment]
@luyajun Thank you for you feedback. May I ask what OS environment you are running eventmesh on? Have you tried dos2unix?

**Comment by luyajun** [comment]
replace the '\r' character , then the start.sh can run.

but the stop.sh can not find the running event mesh , and close it

**Comment by Pil0tXia** [comment]
![image](https://github.com/apache/eventmesh/assets/41445332/1e72cb81-6b7b-4ea2-a271-4875898c1b6b)
 
![image](https://github.com/apache/eventmesh/assets/41445332/68138842-7b27-4058-86f2-dc105b335b87)

In my case it worked with `bash` after dos2unix. The `No Such Process` output was misleading. This problem will be fixed later.

![image](https://github.com/apache/eventmesh/assets/41445332/d9b225be-a19d-4044-8736-0da1366c8277)

The scripts fail when using `sh` even though they are marked with `!/bin/sh` to run with `sh`. This problem is verifying.

**Comment by Pil0tXia** [comment]
@luyajun Your problem will be fixed in https://github.com/apache/eventmesh/pull/4401 and we welcome any further feedback you may have.
