### ISSUE TITLE
Methods that continuously call WeakReference wrapper may throw an NPE

### ISSUE THREAD

**Issue by liutaohua** [apache/eventmesh#446]
All methods using `WeakReference` must check whether it is `NULL` after calling `get()`.

![image](https://user-images.githubusercontent.com/7805272/126107175-25e3b61d-3710-453f-b065-224ec6690e84.png)

**Comment by ruanwenjun** [comment]
Yes, this does happen when the system gc occur, maybe we can use strong reference instead of weak reference.

**Comment by liutaohua** [comment]
> Yes, this does happen when the system gc occur, maybe we can use strong reference instead of weak reference.

I need to continue to understand the business logic in order to understand the author's intentions. 

We can wait for more comments on this question.

**Comment by lrhkobe** [comment]
The weak reference of `ClientGroupWrapper`  in `Session.java`  is designed to avoid circular reference.
Because ClientGroupWrapper contains the reference of Session, and  Session contains the reference of ClientGroupWrapper.

You are right. When system GC occurs, weak references will be recycled, but if the strong reference of ClientGroupWrapper also exists, maybe it will not be a problem. 

We can find strong reference  in the `clientGroupMap` field of  `ClientSessionGroupMapping.java` :
```
private ConcurrentHashMap<String, ClientGroupWrapper> clientGroupMap;
```

**Comment by zzzk1** [comment]
@Pil0tXia, pls assigned this issue to me.

**Comment by Pil0tXia** [comment]
@zzzk1 OK

**Comment by pandaapo** [comment]
Community member explained why the design is like this and why there is no need to worry about the potential weak reference problem. Could anyone explain why this viewpoint is not recognized and this issue must be fixed?

社区成员解释了为什么这样设计以及为什么不需要担心弱引用的潜在问题，谁能解释一下该观点不被认可、必须修复该issue的原因？

**Comment by Pil0tXia** [comment]
Closed after https://github.com/apache/eventmesh/pull/4872#issuecomment-2155856899.
