### ISSUE TITLE
[Enhancement] A poor naming.

### ISSUE THREAD

**Issue by pandaapo** [apache/eventmesh#4521]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

https://github.com/apache/eventmesh/blob/11def17e8bd41c9ff5180926cfdac9aa020af18e/eventmesh-admin/src/main/java/org/apache/eventmesh/admin/enums/Errors.java#L36-L38

A class that defines multiple response states, including `SUCCESS` state, but the class name is `Errors`. Bad smell should be avoided in our codes. Because it will reduce code's readability and maintainability, and also confuse developers.

### Describe the solution you'd like

Change the class name to an appropriate name.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by Asymtode712** [comment]
Hey @pandaapo i want to work on it. Please assign me

**Comment by Asymtode712** [comment]
Thanks @pandaapo for assigning it, just wanted to ask would 'Faults' be an appropriate replacement for 'Errors'

**Comment by Pil0tXia** [comment]
@pandaapo Hi, may I ask if you've seen this reply? https://github.com/apache/eventmesh/pull/4498#discussion_r1367309250

It has already been fixed in https://github.com/Pil0tXia/eventmesh/blob/pil0txia_feat_4501/eventmesh-admin/src/main/java/org/apache/eventmesh/admin/enums/Status.java.

**Comment by Asymtode712** [comment]
@Pil0tXia So should i also do the same for https://github.com/apache/eventmesh/blob/11def17e8bd41c9ff5180926cfdac9aa020af18e/eventmesh-admin/src/main/java/org/apache/eventmesh/admin/enums/Errors.java

**Comment by Pil0tXia** [comment]
@pandaapo Since you've pointed out this issue, I agree with your perspective, and you've also seen my response, so you will definitely find the changes to this class in my next PR. Please rest assured. 😏

**Comment by Asymtode712** [comment]
@pandaapo Please review my PR and suggest if there are some changes to be done.

**Comment by Pil0tXia** [comment]
@pandaapo #4518 has nothing to do with EventMeshAdmin and the changes were made to #4501 in 10.21 immediately after you mentioned naming problem.

#4518 is a quick fix for users. When #4517 was spotted, the naming change has already done.

![image](https://github.com/apache/eventmesh/assets/41445332/2c969d1c-2da9-458f-8891-a31c4f35648e)

**Comment by Pil0tXia** [comment]
@pandaapo #4523 didn't make much change, and it will obviously conflict with #4501. If you find my response reasonable, you can allocate your valuable time to other tasks, and just leave this matter to me.

**Comment by Pil0tXia** [comment]
I had already provided an affirmative response before I submitted the code to my own branch. Since you've also seen that reply, if you're concerned about my development progress or whether I've forgotten about this matter, you can directly reach out to me below my response without the need to create a new issue.

Of course, creating a new issue is also not a problem, and I would promptly explain the situation, indicating that the issue has already been resolved and detailing the plan for its submission along with another PR. Please feel free to proceed.

Please leave this issue for me to resolve.

---

在我向我自己的分支提交代码之前，就已经给您肯定的回复了。既然您也看到了那条回复，如果您关心我的开发进度，以及我有没有忘掉这件事情，您可以直接在我的回复下面联系我，不用再新建一个issue的。

当然，新建一个issue也没什么，我也第一时间跟您解释清楚情况了，说明了这个问题已经被解决了，以及它随另一个PR提交的计划。您大可放心。

这个issue交给我就行，有劳了！

**Comment by Asymtode712** [comment]
@pandaapo I have made all the changes. Please review my PR

**Comment by Pil0tXia** [comment]
@pandaapo  No problem. 👌 https://github.com/apache/eventmesh/pull/4524
