### ISSUE TITLE
[Bug] CodeQL task failed due to enabled build cache

### ISSUE THREAD

**Issue by Pil0tXia** [apache/eventmesh#4737]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux

### EventMesh version

master

### What happened

The CodeQL task is failing when commits do not involve changes to Java source code, likely due to the enabled build cache. This issue has been observed consistently after the commit https://github.com/apache/eventmesh/commit/0be4c7696be2b0b63b7c5da145d15c79dd282d14.

Whenever the CI workflow runs without any changes in the source code, the CodeQL task fails. Examples of such failures can be seen in the following workflow runs:

- https://github.com/apache/eventmesh/actions/runs/7409160388/job/20158858356
- https://github.com/apache/eventmesh/actions/runs/7431611444/job/20222550289
- https://github.com/apache/eventmesh/actions/runs/7442690257/job/20246493029
- https://github.com/apache/eventmesh/actions/runs/7477784932/job/20351265854

### How to reproduce

Push a commit without Java source code change and trigger workflow.

### Debug logs

```java
  /opt/hostedtoolcache/CodeQL/2.15.4/x64/codeql/codeql database finalize --finalize-dataset --threads=4 --ram=14567 /home/runner/work/_temp/codeql_databases/java
  CodeQL detected code written in Java/Kotlin but could not process any of it. Review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build .
  Error: Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.15.4/x64/codeql/codeql database finalize --finalize-dataset --threads=4 --ram=14567 /home/runner/work/_temp/codeql_databases/java". Exit code was 32 and last log line was: CodeQL detected code written in Java/Kotlin but could not process any of it. Review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build . See the logs for more details.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by clayburn** [comment]
I'll take a look

**Comment by clayburn** [comment]
CodeQL does not work for builds where the Java compilation is cached. See [here](https://docs.github.com/en/code-security/code-scanning/troubleshooting-code-scanning/no-source-code-seen-during-build) (Point #4) for more details.

As a quick fix, you can disable build caching on the Java workflows by passing in `--build-cache` at the command line. This will ensure that local builds can continue to benefit from the build cache while getting your CodeQL functionality back. Let me know if you'd like us to submit this.

Longer term, it may be beneficial to restructure the workflows so that CodeQL operates in its own workflow where Java compilation is not cached. I will caveat all of this by saying I've not used CodeQL before, but I could envision a setup where you had only one workflow running CodeQL. This workflow would only need to run the portion of the build that Code QL analyzes. This would have a couple of benefits - your long test builds would be able to leverage the cache, and the parallelization would remove CodeQL from the critical path of your longest builds. What isn't clear to me is if you actually need CodeQL to run on all 4 combinations of Linux/MacOS and Java 8/11, which could change this strategy.

**Comment by Pil0tXia** [comment]
@clayburn 

CodeQL can be run independently in a workflow. 

Is there a simpler way to skip the CodeQL task when there are no changes in the Java source code?

**Comment by clayburn** [comment]
> CodeQL can be run independently in a workflow.

I'm working on a PR to do this. Hope to submit tomorrow during US hours.

> Is there a simpler way to skip the CodeQL task when there are no changes in the Java source code?

I'm not aware of a simple way to do it. It would be possible to write some Gradle logic to detect if all Java compilation came from cache, but I don't see that as "simple". Having CodeQL in its own workflow should make it finish before the tests do, so it won't be on the critical path.
